# Generated by Django 5.1.3 on 2024-11-26 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0003_disasteralert_userprofile_birth_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='disasteralert',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
